/*
 * Data Repository Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: ga4gh-cloud@ga4gh.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DrsService {
    #[serde(rename = "type")]
    pub r#type: Box<models::DrsServiceType>,
}

impl DrsService {
    pub fn new(r#type: models::DrsServiceType) -> DrsService {
        DrsService {
            r#type: Box::new(r#type),
        }
    }
}

